### ISSUE TITLE
Delete

### ISSUE THREAD

**Issue by VPatrick** [VPatrick/PerlArchiver#10]

**Comment by VPatrick** [comment]
Hi,
kannst du in deiner Klasse `Delete` die Methode `verbose(...)` aus der Klasse `Verbosity` verwenden? Dadurch können wir verbose vereinheitlichen.
Danke!

**Comment by KasikciMu** [comment]
@mia8287 
Die Klasse Delete funktioniert auch auf meinem PC perfekt nur hätte ich eine Bitte bei der Frage ob man wirklich die Löschen will steht "file" obwohl ich ein ganzes Archiv lösche. Könntest du das bitte ändern.
Ist nur ein Schönheitsfleck, der mir so aufgefallen ist :D

**Comment by Ramunno** [comment]
Hi hab gesehen das das alle Methoden bei dir public sind! Soll das so sein?

**Comment by Ramunno** [comment]
Destruktor fehlt und Resourcen werden nicht freigeben!

**Comment by Ramunno** [comment]
Haben sich deine Methoden geändert?
Brauche die aktuellen für das Klassendiagramm!

**Comment by Ramunno** [comment]
Deine Methoden sind nicht sehr einheitlich vom Namen! Einmal schreibest du Link und einmal Lnk!

**Comment by mia8287** [comment]
Destruktor eingefügt und Lnk durch Link in den Methoden ersetzt

**Comment by Ramunno** [comment]
Delete funktioniert nicht richtig.
Wenn ich das letzte Archive (neuste) lösche, dann werden zwar die Dateien in das vorhergehenden kopiert, allerdings werden die links in den anderen Archiven davor nicht aktualisiert.

**Comment by Ramunno** [comment]
Wenn eine Archiv gelöscht wird das eine Datei Änderungen zum Nachfolger hat, dann werden die Links in den Vorgänger Archiven nicht aktualisiert!

**Comment by Ramunno** [comment]
Ist es für dich überhaupt wichtig wie das Archiv wirklich heißt heißt? Du bekommst doch nur einen Archivpfad übergeben.

**Comment by KasikciMu** [comment]
@mia8287 
Kannst du dein Delete so anpassen, dass falls es das letzte Archiv ist der Eintrag in der Hashtabelle gelöscht wird.

**Comment by mia8287** [comment]
Erledigt
