### ISSUE TITLE
Restore

### ISSUE THREAD

**Issue by VPatrick** [VPatrick/PerlArchiver#11]

**Comment by VPatrick** [comment]
Hi,
kannst du in deiner Klasse `Restore` die Methode `verbose(...)` aus der Klasse `Verbosity` verwenden? Dadurch können wir verbose vereinheitlichen.
Danke!

**Comment by VPatrick** [comment]
Nimm mal in deiner `Restore`-Klasse das .DS_Store raus. Das ist ne Mac-Spezifische Datei.

**Comment by KasikciMu** [comment]
Tut doch keinem weh :D

**Comment by VPatrick** [comment]
Hast recht :)

**Comment by KasikciMu** [comment]
@VPatrick ich hab jetzt für Restore eine Windows Version hochgeladen kannst du dein Invoker so einstellen dass er je nach Betriebssystem die eine oder andere Klasse benutzt?
Die Funktionen sind die selben!
Danke!

**Comment by KasikciMu** [comment]
Oder du verwendest halt nur die Windows Version da der Referenz-PC eh Windows drauf hat^^
Des andere kannst als Mac Feature oder so mitgeben :D

**Comment by KasikciMu** [comment]
@Ramunno @VPatrick @mia8287 
Hey,
eine Frage ich benutzte das Modul File::Copy::Recursive
wie kann ich das einbinden hat jemand eine Idee?

**Comment by Ramunno** [comment]
Hey,
du hast vergessen use strict zu verwenden.
Das musst du auf jeden Fall noch ergänzen, dadurch werden einige Fehler bemerkbar.

**Comment by Ramunno** [comment]
Übergabeparameter-Variablen beginnen normalerweise mit einem Kleinbuchstaben.

**Comment by KasikciMu** [comment]
use strict wurde hinzugefügt
"normalerweise" ^^

**Comment by Ramunno** [comment]
Ich kann kein use strict sehen!
Hast du es dann auch nochmal getestet?

**Comment by KasikciMu** [comment]
Klar ist strict drinnen und getestet wurde es auch

**Comment by Ramunno** [comment]
Dann hast du es vielleicht mit commited, oder synchronisiert!
Bei mir ist nichts!

**Comment by KasikciMu** [comment]
Ahh sry mein Fehler

**Comment by Ramunno** [comment]
Du hast strict nur bei der Windows Version eingefügt.

**Comment by KasikciMu** [comment]
Ja die Mac Version würde ich etzmal überhaupt nicht betrachten bis zu Präsentation. Danach kann ich des auch erledigen und in dem Bericht erwähnen und mit schicken.

**Comment by Ramunno** [comment]
Ok aber dann nicht vergessen!

**Comment by KasikciMu** [comment]
Ja ist sowieso schnell gemacht (hoffentlich) :D

**Comment by Ramunno** [comment]
Restore gibt seine Ressourcen nicht frei! z.B. verbosity

**Comment by Ramunno** [comment]
Warum hast du die Diagramme auf Englisch gemacht. Ich dachte wir machen die Doku auf Deutsch und nur die Ausgabe im Programm auf Englisch!

**Comment by KasikciMu** [comment]
Aso wusste ich gar nicht kann ich gleich mal ändern.
Ich hätte gedacht bei den Diagrammen ist es egal.

**Comment by KasikciMu** [comment]
Done!

**Comment by Ramunno** [comment]
Restore muss korrigiert werden!

**Comment by Ramunno** [comment]
Warum benötigst du soviel Parameter bei Restore? Würde es nicht reichen es so anzugeben:
perl my_perl_archive.pl -r Archivpfad "Zielpfad mit Verzeichnis" Datum

**Comment by KasikciMu** [comment]
Ich brauch noch den Archivnamen damit ich weiß welches Archiv ich wiederherstellen muss, da das Zielverzeichnis willkürlich gewählt werden kann.
Den Teil mit dem partial benötige ich auch.

**Comment by Ramunno** [comment]
Ah ok in der Doku steht es auch so :-)
Bei mir hat er sich aufgeregt das ich einen Namen ohne date_time erwarte, aber bei Restore schreibt er "Name des Archivs ohne die <date_time> Ergänzung".
Das ist genau das gleich, aber für slim ja nicht ok!!

**Comment by KasikciMu** [comment]
Jo ich glaub der Typ mag dich überhaupt nicht :D

**Comment by Ramunno** [comment]
Wer weiß, hast du dein Restore schon angepasst?

**Comment by KasikciMu** [comment]
Ja aber noch nicht hochgeladen ich programmier des jetzt alles auf Windows und lad es dann so am Wochenende hoch wenn ich komplett fertig bin.
Ich hab deine Funktion verwendet womit man die Orginaldatei findet und eine eigene Funktion geschrieben die dann jede Datei einzeln kopiert.

**Comment by Ramunno** [comment]
Warum machst du es nicht so, das du anstelle des Namens des Archives das du wiederherstellen willst, den Pfad des Originals angibst und daraus den Hash berechnest oder in der Datei nachschaust

**Comment by Ramunno** [comment]
Ok

**Comment by KasikciMu** [comment]
Versteh ich nicht welche Datei, meinst du die Text-Datei?

**Comment by Ramunno** [comment]
Ich habe Fehlermeldungen bekommen!
Global symbol "$tmp" requires explicit package name at RestoreWin.pm line 339.
Global symbol "$tmp" requires explicit package name at RestoreWin.pm line 341.
Global symbol "$flag" requires explicit package name at RestoreWin.pm line 377.

**Comment by Ramunno** [comment]
Ich habe den Fehler entfernt! Hattest bei $temp das my davor vergessen und $flag sollte $Flag heißen!

**Comment by KasikciMu** [comment]
@Ramunno Danke :D
