### ISSUE TITLE
Abschlusspräsentation

### ISSUE THREAD

**Issue by VPatrick** [VPatrick/PerlArchiver#12]

**Comment by VPatrick** [comment]
Als Ausblick könnte man auch diverse Verbosity-Level mit aufnehmen.

Jeder seine eigenen Folien, Vortragen tut jeder seins. ==> Da baut sich jeder seine Folien und dann fügen wir das in einer Präsentation zusammen oder machen wir dann unterschiedliche Präsentationen?

**Comment by Ramunno** [comment]
Ich würde vorschlagen das wir einen Foliensatz haben. Der Inhalt der Folien wird von jedem selber gemacht. Und die werden dann zusammen auf eine Foliensatz gemacht.
Es sollten auch nicht zuviel Folien von jedem sein, würde sagen max. 3 pro Use-Case.
Der Inhalt der Folien sollte vielleicht eine kurze Vorstellung der Methoden und Aktivitätsdiagramm sein.
Oder habt ihr eine bessere Idee?

**Comment by VPatrick** [comment]
:+1: Passt

**Comment by KasikciMu** [comment]
Die Performance-Analyse würde ich bei der Hauptpräsentation reinsetzten das die zweite Präsentation nur das Programm sein soll. Oder hab ich da was falsch verstanden.
Wir könnten einfach die Analyse-Ergebnise nach den jeweiligen Klassen vorstellen ist ja nicht viel.

**Comment by KasikciMu** [comment]
@VPatrick @mia8287 @Ramunno 
Treffen wir uns morgen wieder in der Uni und testen einmal die Software und setzten die Teilpräsentation zusammen sodass wir Dienstag keinen Stress haben.
Ich könnte wieder ab 14:30

**Comment by VPatrick** [comment]
Wenn ich morgen komm, dann eher spontan, weil ich meine Freundin morgen irgendwann vom Arzt abholen muss.
Weiß leider noch nicht genau wann.
Wenn ichs schaff, dann komm ich so gegen 14:30 Uhr ins Mac-Labor.

LG Patrick

**Comment by Ramunno** [comment]
Also ich habe morgen keine Zeit! Ich bin erst wieder am Dienstag in der Uni! Habe aber wahrscheinlich schon ab 11:30 Zeit!
Hab ihr jetzt das Klassendiagramm angeschaut?

**Comment by KasikciMu** [comment]
Ok dann wäre es aber nett wenn ihr eure Präsentationen trotzdem bis morgen fertig habt dann kann ich sie wenigstens zusammenfügen damit wir am Dienstag nicht soviel zu tun haben.

**Comment by KasikciMu** [comment]
Klassendiagramm passt bei Restore :+1:

**Comment by VPatrick** [comment]
Klassendiagramm passt für meine Klassen auch!

**Comment by mia8287** [comment]
Ich weiß noch nicht, wann ich es morgen schaffe, muss für meine andere Prüfung am Dienstag noch einiges machen. Denke es ist wichtig, dass wir nochmal testen, ob es wirklich auf den Rechnern funktionieren. Es ist übrigens cygwin mit perl 5.14 installiert.
Am Dienstag habe ich bis 13:10 Prüfung und danach hätte ich Zeit.

Im Klassendiagramm hat sich bei noch alle "Lnk" durch "Link" geändert. Denke ansonsten passt es.

**Comment by KasikciMu** [comment]
Dann bleib ich morgen auch daheim.
Wie gesagt wäre super wenn ihr eure Teilpräsentationen bis morgen fertig hättet, sodass ich sie zusammensetzten kann.

**Comment by mia8287** [comment]
Hat von euch nochmal jemand getestet, ob alles am PC der Hochschule funktioniert oder machen wir das morgen zusammen?

**Comment by VPatrick** [comment]
Durch die Cygwin-Installation ergibt sich, dass wir eine Meldung bekommen, dass das System normale Slashes (/) Backslashes (\) vorzieht. Die Eingabe von Pfaden funktioniert aber nur mit Backslashes!

Die Meldung beeinträchtigt den Programmablauf aber nicht.

@mia8287 Es gibt immer noch eine grobe Fehlermeldung, die  deine Delete-Klasse betrifft: Issue #29

**Comment by KasikciMu** [comment]
@VPatrick hast du die Restore Klasse auch schon getestet?

**Comment by VPatrick** [comment]
Bin leider nicht mehr dazugekommen. Müssen wir morgen machen. Es gab aber keine offensichtlichen Fehlermeldungen. Die Anwendung konnte kompilieren.

**Comment by KasikciMu** [comment]
@Ramunno @VPatrick @mia8287 
Ich hab völlig vergessen das ich die alte Version von Keynote habe weil ich das alte Betriebssytem noch drauf hab. Wäre nett wenn einer von euch die Präsentationen zusammenfügen könnte.
An Alle:
Da die Diagramme (in meinem Fall) zu groß für die Präsentation werden, muss wahrscheinlich einer während der Präsentation am Laptop sitzen und rumnavigieren.

**Comment by Ramunno** [comment]
Meine sind auch zu groß!

**Comment by KasikciMu** [comment]
@Ramunno bist du dann morgen um 11:30 in der Uni?

**Comment by Ramunno** [comment]
Create Präsentation ist im Git

**Comment by Ramunno** [comment]
Ja bin ab 11:30 im Labor

**Comment by KasikciMu** [comment]
@VPatrick @mia8287 
Wir sind im HQ412
