### ISSUE TITLE
Verbosity

### ISSUE THREAD

**Issue by Ramunno** [VPatrick/PerlArchiver#14]
Du solltest für den Level einen default Wert verwenden, der im Konstruktor gesetzt wird. Wenn man das beim Konstruktor vergisst bekommt man einen Fehler. 
Use of uninitialized value in numeric gt (>) at Verbosity.pm line 23.

**Comment by VPatrick** [comment]
0a44935 done!

**Comment by Ramunno** [comment]
Die Farbausgabe funktioniert nicht unter Windows.
Entwickelst du unter Mac OS? Wenn ja, sollten du aufpassen!
Der Referenz-PC ist ein Windows-System! Ich habe auch ein paar Probleme mit Create deswegen!

**Comment by VPatrick** [comment]
Müsste jetzt auf Mac, Linux und Windows laufen. Werde es leider erst am Mittwoch unter Windows testen können.

**Comment by Ramunno** [comment]
Willst du vielleicht die Verbosity Klasse so anpassen, dass wir 2 Level haben.
Level 0: Keine Ausgabe
Level 1: Ausgabe von Kopieren, Löschen oder Verzeichnis erstellen/wechsel und so.
Level 2: Debug Ausgabe, also alles mögliche
Damit man nach der Fehlersuche die Ausgaben nicht mehr entfernen muss!

**Comment by VPatrick** [comment]
Hab das jetzt mal umgesetzt aber noch nicht getestet.
Level 0: Keine Ausgabe
Level 1: Ausgabe der Funktionen
Level 9: Debug --> Es bleiben somit Level 2 .. 8 für andere Ausgaben frei!

**Comment by KasikciMu** [comment]
@VPatrick 
Hey schau mal in deinem Konstruktor bei message da steht glaubich
message = Message->new,
sollte eigentlich
message => Message->new(0),
sein.

**Comment by Ramunno** [comment]
@VPatrick 
Verbosity geht nicht mehr!
Fehlermeldung:
Can't modify constant item in scalar assignment at Verbosity.pm line 19, near "->new
	}"
Ich glaube du musst das was der Muhammed schon gesagt hat ändern, du schreibst nur = und nicht =>
in Zeile 18.
Außerdem kommt keine Ausgabe bei level=1. 
Da musst du die Abfrage in Zeile 45 ändern:
aktuell: if ($self->{level} > 1) 
geändert:if ($self->{level} >= 1) {

**Comment by VPatrick** [comment]
gefixt

**Comment by Ramunno** [comment]
Ausgabe funktioniert immer noch nicht bei Level 1

**Comment by VPatrick** [comment]
level 1 müsste jetzt auch funktionieren

**Comment by Ramunno** [comment]
Ja geht

**Comment by Ramunno** [comment]
Destruktor fehlt! Ressourcen freigeben: message!

**Comment by VPatrick** [comment]
done
