### ISSUE TITLE
Ausgabesprache

### ISSUE THREAD

**Issue by VPatrick** [VPatrick/PerlArchiver#15]
@KasikciMu, @mia8287, @Ramunno 

Hi,
wir sollten uns wohl auf eine Sprache für Ausgaben einigen.
Entweder Deutsch oder Englisch.
Für was seid ihr?

**Comment by KasikciMu** [comment]
Englisch

**Comment by VPatrick** [comment]
Bin auch für Englisch

**Comment by mia8287** [comment]
Bin auch für Englisch

**Comment by VPatrick** [comment]
Dann sind wir uns ja mit Englisch einig.
