### ISSUE TITLE
Referenz-PC

### ISSUE THREAD

**Issue by Ramunno** [VPatrick/PerlArchiver#16]
Hi,
was für ein Betriebssystem benutzt ihr für die Entwicklung?
Der Referenz-PC ist ein Windows, dass heißt das Programm muss dort laufen.
Falls ihr mit etwas anderem als Windows entwickelt, dann testet es auf jeden Fall unter Windows nochmal. Ich habe Probleme beim meinem Create Modul deswegen, weil Windows eine anderes Verzeichnisformat verwendet!

**Comment by VPatrick** [comment]
Entwicklung: Mac OS X 10.10.1
Test: Windows 8

**Comment by KasikciMu** [comment]
Entwicklung Mac OS X 10.9.5
Test: Windows 7
