### ISSUE TITLE
Message

### ISSUE THREAD

**Issue by Ramunno** [VPatrick/PerlArchiver#17]
Message bring Compiler Fehler!
Global symbol "$self" requires explicit package name at Message.pm line 28.
BEGIN not safe after errors--compilation aborted at Message.pm line 29.
Compilation failed in require at Verbosity.pm line 3.
BEGIN failed--compilation aborted at Verbosity.pm line 3.

**Comment by VPatrick** [comment]
Done! 612bb8d

**Comment by Ramunno** [comment]
Message hat keinen Destruktor!

**Comment by Ramunno** [comment]
Du hattest mir am Mittwoch gesagt das Message eine Aggregation zu Utils hat. Ich kann aber nichts entdecken!

**Comment by VPatrick** [comment]
Des weiß ich doch net was das für UML zeug ist. In Message hängt auf alle Fälle nix mehr von Utils.

**Comment by Ramunno** [comment]
Ok anders, Message benutzt nicht Utils!
