### ISSUE TITLE
Archivname

### ISSUE THREAD

**Issue by KasikciMu** [VPatrick/PerlArchiver#18]
Da es Unstimmigkeiten bei der Vergabe der Archivnamen gibt wollt ich mal wissen wie eure Archivnamen aussehen.

Also mein Restore akzeptiert:
sourcename_2014_01_28_17_45_22

Danke

**Comment by Ramunno** [comment]
"Pfad woher das Verzeichnis kommt"_<date_time>
also
C_Users_Hein_Data_2014_12_19_10_29_55

Hatte ich damals geändert auf Anfrage von @mia8287 

Laut Aufgabenstellung: ["SOURCE ist der Name des Quellverzeichnisses."]

**Comment by KasikciMu** [comment]
Ich versteh gerade den Sinn nicht von so einem bescheuerten Namen.
Also ich mein was für ein Vorteil soll ich aus dem Namen ziehen?

**Comment by VPatrick** [comment]
Ich denk der Name ist egal oder? Wenn ich mein Verzeichnis ABC nennen will dann nervt mich der rest nur.

**Comment by mia8287** [comment]
In der Angabe steht, dass der Name das Quellverzeichnis ist und bei meinem Code ist es wichtig, dass nicht alle Archive gleich heißen und nur von der Zeit unterschiedlich sind. Sonst muss ich jeden Ordner nach relevanten Verknüpfungen durchsuchen. Wenn das Archiv den Sourcenamen übernimmt, muss ich nur die Archive mit dem gleichen Namen durchsehen.

**Comment by Ramunno** [comment]
Ich würde mal vorschlagen das wir uns mal zusammensetzen und alle Probleme klären. Da wir nicht mehr so lange Zeit haben sollten wir es so schnell wie möglich machen.
Habt ihr morgen (Mittwoch) mal ne Stunde Zeit. Ich habe ab 11:30 Zeit.

**Comment by KasikciMu** [comment]
Ich könnte am Mittwoch erst ab 14:30

**Comment by mia8287** [comment]
Ich kann auch erst ab 14 Uhr

**Comment by KasikciMu** [comment]
Meiner Meinung nach treffen wir uns morgen und stellen alle Programme fertig und fangen endlich mit der Präsentation an egal wie lange es morgen dauert!

**Comment by VPatrick** [comment]
Hab morgen ab 11:30 Uhr bis 15:45 Uhr zeit. Wir sollten das morgen auf alle Fälle klären und soweit es geht fertigstellen. Ich hätte auch noch ein paar Punkte anzusprechen.

**Comment by Ramunno** [comment]
Ok also Patrick wir sehen uns dann morgen auf jeden Fall schon mal um 11.30 im Mac Labor.

**Comment by mia8287** [comment]
Ich kann erst um 14:00 los, werde also erst 14:30 da sein
