### ISSUE TITLE
Can't locate File/Copy/Recursive.pm

### ISSUE THREAD

**Issue by VPatrick** [VPatrick/PerlArchiver#21]
Can't locate File/Copy/Recursive.pm in @INC (you may need to install the File::Copy::Recursive module) (@INC contains: /Users/pvogt/Dropbox/TH Nürnberg/5. Semester/SysProgPerl/PerlArchiver/PerlArchiver/source /Library/Perl/5.18/darwin-thread-multi-2level /Library/Perl/5.18 /Network/Library/Perl/5.18/darwin-thread-multi-2level /Network/Library/Perl/5.18 /Library/Perl/Updates/5.18.2 /System/Library/Perl/5.18/darwin-thread-multi-2level /System/Library/Perl/5.18 /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level /System/Library/Perl/Extras/5.18 .) at Restore.pm line 11.

Wir sollten solche Module irgendwie mit in unsere Programm nehmen. Kannst du das direkt in unser Source-Verzeichnis rein machen?

**Comment by KasikciMu** [comment]
So ich musste im source Ordner einen Ordner "File" erstellen und in diesen noch einen Ordner "Copy" und in diesen musste ich Recursive.pm reinstellen damit es problemlos funktioniert^^
