### ISSUE TITLE
Hochschule PC

### ISSUE THREAD

**Issue by KasikciMu** [VPatrick/PerlArchiver#22]
Also ich wollte heute unsere Klassen testen und es hat gar nichts funktioniert ^^
Ich habe sogar ein einfaches Programm das "Hallo" ausgibt geschrieben und probiert auszuführen. Leider ging dieses Programm auch nicht.
Ich hab dem Hein jetzt eine E-Mail geschrieben und warte noch auf seine Antwort.

**Comment by VPatrick** [comment]
Das klingt nicht gut. Ich werd mir morgen das System im Labor auch noch mal anschauen.

**Comment by KasikciMu** [comment]
@VPatrick @mia8287 @Ramunno 
Hey Leute kann einer von euch diese E-Mail über euren Hochschule E-Mail an den Hein senden :D 
Leider hab ich mein Passwort vergessen und kann nicht mehr darauf zugreifen^^
Hier die E-Mail


Sehr geehrter Prof. Dr.-Ing. Hein,

nachdem meine Gruppe die Module und Klassen für unser Projekt erstellt
haben wollte ich diese an den PC im Labor HQ412 testen. Als ich ein
Perl-Programm starten wollte (Standardprogramm: SWIProlog) wurden
mehrere Fehlermeldungen ausgegeben.
Kurz darauf hab ich ein folgendes einfaches Perl-Programm geschrieben:

use warnings;

print "Hallo!\n";

und es wurde folgende Fehlermeldung ausgegeben:

ERROR:
//mycloud.informatik.fh-nuernberg.de/students/kasikcimu53126/desktop/Test.pl
: 3:15: Syntax error: Unexpected end of file

Leider konnte Ich in diesem Programm keinen Fehler finden.
Könnten Sie mir bitte bei diesem Problem helfen.
Danke!

Mit freundlichen Grüßen
Muhammed Kasikci


PS.: Ihr könnt auch euren eigenen Namen hinschreiben solange der Hein die E-Mail bekommt :D

**Comment by mia8287** [comment]
Denke wir können ja die nächsten Tage nochmal testen bevor wir ihm schreiben. Habe gerade einen Fehler bei mir bemerkt, wodurch das delete in der jetzigen Form nicht funktionieren kann, weil Windows den Pfad mit \ angibt und in meiner main war der Pfad immer mit / schon gegeben.

**Comment by VPatrick** [comment]
Wir sollten alle möglichen Fehler ausschließen und auch das Referenz-System nochmal testen. Spätestens am Montag sollten wir uns aber an den Hein wenden wenn dann immer noch nix geht.

**Comment by mia8287** [comment]
Habe heute mal an der Hochschule an den PCs getestet. "Hello World" hat funktioniert, aber es kommt immer die Meldung:

perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LC_ALL = (unset),
        LANG = "DE"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").

Wenn man my_perl_archive.pl -h ausführt, kommt zusätzlich noch diese Meldung:

Can't modify constant item in scalar assignment at Verbosity.pm line 19, near "-
>new
        }"
Compilation failed in require at Invoker.pm line 3.
BEGIN failed--compilation aborted at Invoker.pm line 3.
Compilation failed in require at my_perl_archive.pl line 12.
BEGIN failed--compilation aborted at my_perl_archive.pl line 12.

**Comment by VPatrick** [comment]
Fehler in Verbosity.pm gefixt

**Comment by VPatrick** [comment]
Folgende Funktionen funktionieren: List (-l), Create (-c)
Fehlerhafte Funktionen: Create+Slim (-cs), Delete (-d)

Die anderen Funktionen müssen noch getestet werden (-r, -rp, -s)

**Comment by mia8287** [comment]
Was sind denn die Fehlermeldungen bei -cs und -d?

**Comment by VPatrick** [comment]
-d siehe Issue #29 und -cs muss ich mir nochmal anschauen. Da passt vermutlich am Invoker was nicht.

**Comment by Ramunno** [comment]
Geht create_cs jetzt?

**Comment by VPatrick** [comment]
@KasikciMu , @mia8287 , @Ramunno 
Wollen wir uns kommende Woche nochmal zum Testen im Labor treffen?
Wenn ja, dann macht doch bitte auch gleich Terminvorschläge.

**Comment by mia8287** [comment]
Mir würde es am Dienstag am besten nach SoftA passen.

**Comment by KasikciMu** [comment]
Für mich wär es am besten am Mittwoch nach Compiler Prüfung die würde um 11 Uhr beginnen

**Comment by Ramunno** [comment]
Ich würde auch Dienstag bevorzugen, zum einen bin ich nur Dienstag an der TH und zum anderen haben wir dann mal ein bisschen Puffer falls was nicht gehen sollte.
Ich habe ab 9:45 Zeit, also nach SoftA!

**Comment by KasikciMu** [comment]
Dienstag kann ich erst ab 11:30 hab noch Compiler Prüfungsvorbereitung

**Comment by VPatrick** [comment]
Ich hab auch am Dienstag ab 09:45 Uhr Zeit. Dann treffen wir uns also am Dienstag ab 09:45 im Labor. @KasikciMu Du kannst ja dann nachkommen.

**Comment by KasikciMu** [comment]
Ok
