### ISSUE TITLE
List

### ISSUE THREAD

**Issue by Ramunno** [VPatrick/PerlArchiver#24]
List hat keinen Destruktor!

**Comment by Ramunno** [comment]
List gibt seinen Ressourcen nicht frei! verbosity, message, utils

**Comment by VPatrick** [comment]
Hat jetzt einen Konstruktor der die Ressourcen frei gibt!

**Comment by Ramunno** [comment]
Musst du nicht zum Freigeben Instanz->destroy() aufrufen?

**Comment by VPatrick** [comment]
Ich denk es ist nicht nötig die Ressourcen frei zugeben weil das der Garbage Collector doch übernimmt oder?

**Comment by Ramunno** [comment]
Keine Ahnung! Gibt es überhaupt einen Garbage Collector bei der Perl Laufzeit Umgebung?
Für was sollte sonst der Destruktiv gut sein?

**Comment by Ramunno** [comment]
Ausserdem hatte der Hein gemeint das jede Klasse Destry implementieren muss.

**Comment by VPatrick** [comment]
Jap, gibt einen GC für die Perl Runtime.

**Comment by Ramunno** [comment]
Ok, d.h. es reicht wenn man der variablen undef zuweist?

**Comment by VPatrick** [comment]
In Vorlagen hab ich gesehen, dass die das mit `$self->{xyz} = undef;` machen

**Comment by Ramunno** [comment]
Woher weiß List welches Archiv du meinst, also ob C_Data  oder  C_Documents ?
perl my_perl_archive.pl -v -l C:\Users\Home\Desktop\source\TestArchiv 2015_01_13_22_33_26

Ich habe folgende Fehlermeldung bekommen, wenn ich versuche ein Archiv auszugeben.

Use of uninitialized value $date in split at Utils.pm line 69.
Use of uninitialized value $y in concatenation (.) or string at Utils.pm line 70.
Use of uninitialized value $m in concatenation (.) or string at Utils.pm line 70.
Use of uninitialized value $d in concatenation (.) or string at Utils.pm line 70.
Use of uninitialized value $H in concatenation (.) or string at Utils.pm line 70.
Use of uninitialized value $M in concatenation (.) or string at Utils.pm line 70.
Use of uninitialized value $S in concatenation (.) or string at Utils.pm line 70.
Argument "" isn't numeric in numeric le (<=) at Utils.pm line 49.
Use of uninitialized value $archiveTimestamp in concatenation (.) or string at Utils.pm line 50.

**Comment by VPatrick** [comment]
Es wird nicht das Archiv-Verzeichnis, das Archive sammelt angegeben, sondern ein Pfad zu einem Archiv.
perl my_perl_archive.pl -v -l C:\Users\Home\Desktop\source\TestArchiv\ARCHIVE TIMESTAMP

**Comment by VPatrick** [comment]
Kann den Fehler nicht nachvollziehen. Erscheint bei mir nicht.

**Comment by VPatrick** [comment]
done
