### ISSUE TITLE
Invoker

### ISSUE THREAD

**Issue by Ramunno** [VPatrick/PerlArchiver#26]
Laut Code benutzt Invoker gar nicht direkt create, sondern über instances. Ist das richtig?

**Comment by VPatrick** [comment]
Stimmt so, da für Create und Slim genau eine Instanz (eine Art Singleton) von `Create` erzeugt wird.

**Comment by VPatrick** [comment]
Bei Restore ist das dasselbe!

**Comment by Ramunno** [comment]
Ich habe bei Invoker das Problem mit dem delete import unter Unix entfernt.
Kannst du für create_s im Invoker den Archivenamen aus der Destination herausfiltern, also Pfad und date_time entfernen und das dann an addArchiveName übergeben?
z.B. C:\Data\Archiv\C_Date_Test_2015_13_01_20_00_00  =>  addArchiveName(C_Date_Test)
Wobei ich aus dem Namen schon einen Hash gemacht habe!

**Comment by VPatrick** [comment]
Das heißt -s erwartet jetzt nur noch einen Parameter?
=> perl my_perl_archive.pl -s ../TestArchiv/Users_pvogt_Dropbox_TH\ Nürnberg_5.\ Semester_SysProgPerl_PerlArchiver_Test_2015_01_13_12_27_48

Den Namen muss ich dann noch hashen, oder?

**Comment by VPatrick** [comment]
@Ramunno , @KasikciMu , @mia8287 
Könnt ihr mir bitte schreiben was eure Methoden für Parameter erwarten. Pfade oder Hashes?
@Ramunno  Kannst du mir bitte sagen wo ich die Datei zur Zuordnung von Pfaden finden kann.

**Comment by mia8287** [comment]
Ich bräuchte weiterhin den absoluten Pfad zum Archiv und die Angabe des Archivs mit evtl. zu löschendem Unterordner oder Datei.

**Comment by VPatrick** [comment]
@mia8287
Demnach bleibt alles so wie es war, oder?
Ein weiterer Punkt: Wie gehst du mit relativen Pfaden um? Das hat der Hein doch bemängelt.

**Comment by mia8287** [comment]
Ja bei der Übergabe kann alles so bleiben. Also ich bräuchte den absoluten Pfad, dachte der Invoker macht relative Pfade zu absoluten Pfaden, da es wenig Sinn macht, wenn jedes Modul eine Funktion hat mit der relative Pfade zu absoluten gemacht werden.

**Comment by VPatrick** [comment]
Ok.
Dann bau ich das noch in den Invoker ein.

**Comment by Ramunno** [comment]
@VPatrick Die Zuordnung kannst du noch gar nicht finden, hab ich noch nicht gemacht.
Ich mache das jetzt. Würde vorschlagen, dass ich sie in einer Datei im Verzeichnis ablege.
also z.B. C:\Users\Home\Desktop\source\TestArchiv 
Wie soll ich die Datei den nennen?
Format ist jetzt: Hash:Verzeichnis

**Comment by VPatrick** [comment]
Nenn Sie doch .hashtable.txt oder so. Würde vorschlagen, dass dann eine nicht-sichtbare Datei ist. Was haltet ihr davon?

**Comment by KasikciMu** [comment]
Ich brauch Folgendes:
* Das Quellverzeichnis (also den absoluten Pfad zu den Archiven)
* Das Zielverzeichnis (den absoluten Pfad wohin es reinkopiert werden soll)
* Eine date_time Angabe
* Den Namen des Archivs (den kann ich dan selbst in der .txt nachschauen welcher Hash es ist)
* Für Partial erwarte ich einen relativen Pfad 

Das mit dem restore_rp() muss du noch irgendwie einbauen hat ja letztes mal nicht funktioniert!

**Comment by Ramunno** [comment]
Aber wenn sie nicht sichtbar ist, kann der Anwender nicht herausfinden welche Hash was ist.
Dann müssten wir schon ein Ausgabe für die Zuordnung machen.

**Comment by VPatrick** [comment]
Hm... dann lass sie sichtbar. Dachte nur, dass das nicht so interessant sei. Mich persönlich stören immer Dateien, die von ner Anwendung automatisch angelegt wurden und nicht unsichtbar sind.

**Comment by Ramunno** [comment]
Ich kann sie ja unsichtbar machen, aber dann muss der invoker die Ausgabe zur Verfügung stellen.
Wäre ja nur ein auslesen und Ausgeben auf Konsole

**Comment by VPatrick** [comment]
Über nen eigenen Switch oder wie?

**Comment by Ramunno** [comment]
Ja z.B., ich weiß aber nicht wie ich die Datei in Windows versteckt mache

**Comment by VPatrick** [comment]
Macht ma des da net mit nem Punkt vor dem Dateinamen?

**Comment by VPatrick** [comment]
@KasikciMu 
Bzgl. deiner Zeile: Den Namen des Archivs (den kann ich dan selbst in der .txt nachschauen welcher Hash es ist)

Brauchst du dann nur noch 3 Parameter für Restore und 4 für Restore + Partial?

**Comment by KasikciMu** [comment]
Nein 4 für Restore und 5 für Restore+Partial
Ich hab des so gemeint, dass ich anhand des Namen über die Tabelle nachschauen kann welcher Hash es ist

**Comment by KasikciMu** [comment]
@VPatrick wir müssten noch die Methode findLastValidArchive() so verändern das es auch den Hash als Übergabeparameter an nimmt. Weil zur Zeit nimmt er einfach je nach date_time ein Archiv. Aber da nach unserem Schema Archive mit verschiedenen Pfaden in dem Archiv Ordner sein können müssen wir auch unterscheiden welches Archiv nun gewählt wurde.
Ich hoffe ich konnte es erklären^^

**Comment by VPatrick** [comment]
Hab ich heute schon so umgesetzt. Der Aufruf erfolgt so: `findLastValidArchive(source, timestamp, name)`

**Comment by VPatrick** [comment]
@KasikciMu 
Bzgl.: Ich hab des so gemeint, dass ich anhand des Namen über die Tabelle nachschauen kann welcher Hash es ist

Hab da ne Methode in der Utils Klasse `getPathFromHash(hash, Pfad zur Hashdatei)` die dir einen Pfad zu einem Hash gibt.

**Comment by KasikciMu** [comment]
@VPatrick 
Also 'findLastValidArchive(source, timestamp, name)' nimmt den Namen und schaut intern nach dem Hash und danach gibt er mir den Pfad zu dem Archiv?
Hab ich das so richtig verstanden?

**Comment by KasikciMu** [comment]
Weil ich gebe bei 'name' den Hash mit sodass er mir das richtige Archiv zurück gibt

**Comment by VPatrick** [comment]
Die Methode vergleicht alle Archive die mit dem übergebenen 'name' (egal ob Hash oder sonst irgendwas) beginnen. Unter denen die mit dem Wert beginnen nimmt er das zuletzt gültige. Das bekommst du dann als Pfad zurück.

**Comment by KasikciMu** [comment]
@VPatrick  Sehr gut dann hab ich es ja richtig benutzt :D 
Hast du die Methode so verändert dass es "\" macht anstatt "/"?

**Comment by Ramunno** [comment]
@VPatrick welche Parameter muss ich jetzt bei slim angeben?

**Comment by VPatrick** [comment]
@KasikciMu : Die Methode mach bei Windows "\" und bei allen anderen "/"
@Ramunno : Bei Slim musst du den Pfad zu einem Archiv angeben.

**Comment by Ramunno** [comment]
Mit Archiv also so:
C:\Users\Home\Desktop\source\TestArchiv\0ceea58a84cdcac31df287784cc9e0b9_2015_01_17_16_25_48
oder so:
C:\Users\Home\Desktop\source\TestArchiv

**Comment by VPatrick** [comment]
Ersteres, weil ich ja den Archivnamen extrahieren sollte.

**Comment by Ramunno** [comment]
Create s funktioniert nicht richtig, du muss bei addDestination nur 
C:\Users\source\TestArchiv 
übergeben.

**Comment by VPatrick** [comment]
Müsste jetzt passen.

**Comment by Ramunno** [comment]
Ne geht immer noch nicht

**Comment by VPatrick** [comment]
Dann liegts aber nicht am Invoker. Ich steck folgende Daten in deine Methoden:
* /Users/pvogt/Dropbox/TH Nürnberg/5. Semester/SysProgPerl/TestArchiv
* a48f7812976b4b8fd24879858e7c3f5c_2015_01_17_19_05_22

**Comment by VPatrick** [comment]
@Ramunno Wie siehts jetzt mit Slim aus? Passen die übergebenen Daten so?

**Comment by Ramunno** [comment]
Programm geht nicht mehr! Irgendjemand hat Restore gelöscht!
Fehlermeldung:
Can't locate Restore.pm in @INC (you may need to install the Restore module) (@INC contains: Instances.pm line 48.

**Comment by Ramunno** [comment]
Ich glaube slim geht nicht, als ich es gestern getestet hatte habe ich immer den Pfad mit Archivverzeichnis bekommen. Wenn das Programm wieder geht kann ich es nochmal testen!

**Comment by KasikciMu** [comment]
Ihr sollt RestoreWin.pm nutzen.

**Comment by VPatrick** [comment]
Wenn das System ein MSWin32 ist, dann wird RestoreWin benutzt anderenfalls das normale Restore. Ist das normale Restore nicht mehr verwendbar?

**Comment by KasikciMu** [comment]
Nein leider nicht mehr wenn ich es noch vor der Abgabe programmiern kann dann schon. Falls nicht dann geht Restore nur für Win.

**Comment by VPatrick** [comment]
Restore.pm wurde durch den Commit 2a40e1c von @KasikciMu gelöscht.
@KasikciMu Warum hast du Restore.pm gelöscht?

**Comment by KasikciMu** [comment]
Ich müsste noch alles was ich bei RestoreWin gemacht hatte auf Restore auch machen. Wie gesagt frühestens vor Abgabe auf Windows müsste es funktionieren

**Comment by VPatrick** [comment]
Ok, dann musst du sowas aber auch schreiben. Muss ja den Invoker usw. anpassen.

**Comment by KasikciMu** [comment]
@VPatrick 
Sry mein Fehler

**Comment by VPatrick** [comment]
Also: Problem behoben. Die Anwendung läuft wieder!

**Comment by Ramunno** [comment]
Slim geht nicht, es wird folgendes bei addDestination hinzugefügt:
C:/Users/source/TestArchiv/d22cd2cc059df681c1a38d9c510fdb85_2015_01_17_21_24_34
sollte aber nur
C:/Users/source/TestArchiv
sein

**Comment by VPatrick** [comment]
Also bei mir werden die richtigen Parameter übergeben. Du hast dann wohl nicht die aktuelle Version vom Invoker! Prüf das mal!

Hier ein Link zur aktuellen Version: https://github.com/VPatrick/PerlArchiver/blob/master/source/invoker.pm

**Comment by Ramunno** [comment]
Doch habe ich.
Ich rufe es mit 
my_perl_archive.pl -v -s ../../TestArchiv/d22cd2cc059df681c1a38d9c510fdb85_2015_01_17_21_24_34 auf.

**Comment by VPatrick** [comment]
Dann muss es funktionieren! Kopier mir mal bitte die slim-Methode des Invokers hier rein.
