### ISSUE TITLE
Instances

### ISSUE THREAD

**Issue by Ramunno** [VPatrick/PerlArchiver#27]
Instances erzeugt keine Instanz von Restore! Code ist auskommentiert!

**Comment by Ramunno** [comment]
Außerdem fehlt ebenfalls der Destruktor!

**Comment by VPatrick** [comment]
Instances braucht keinen Destruktor! Sobald das Objekt nicht mehr benötigt wird, räumt der GC auf!

**Comment by VPatrick** [comment]
Restore ist wieder einkommentiert!
