### ISSUE TITLE
utils.pm Fehlmeldungen

### ISSUE THREAD

**Issue by mia8287** [VPatrick/PerlArchiver#28]
Bekomme immer die Meldung: 

Subroutine new redefined at C:/Users/Michaela/PerlArchiver/source/utils.pm line 13.
Subroutine setVerboseLevel redefined at C:/Users/Michaela/PerlArchiver/source/utils.pm line 26.
Subroutine findLastValidArchive redefined at C:/Users/Michaela/PerlArchiver/source/utils.pm line 35.
Subroutine compare_to redefined at C:/Users/Michaela/PerlArchiver/source/utils.pm line 68.
Subroutine DESTROY redefined at C:/Users/Michaela/PerlArchiver/source/utils.pm line 75.

und create -s  und delete funktionieren nicht. Ist das nur bei mir so?

**Comment by KasikciMu** [comment]
Bei Utilis.pm im Konstruktor wird das verbositiy-Objekt falsch angelegt.
Statt
verbosity -> Verbosity->new
sollte
verbosity -> Verbosity->new(),
stehen.

Was bei Create -s und delete nicht funktioniert weiß ich nicht. Das letzte mal als ich beide getestet habe, hat alles perfekt funktioniert.

**Comment by VPatrick** [comment]
Der Konstruktor-Aufruf ist schon richtig und funktioniert auch. Das ist nur ne alternative Schreibweise wenn keine Parameter übergeben werden.

Hab grad versucht die Fehlermeldung zu verstehen und zu beheben bin aber bei beiden Punkten gescheitert :(

Habt ihr ne Idee woran das liegen könnte?

**Comment by mia8287** [comment]
Also das mit den Klammern macht bei mir keinen Unterschied. Ist die Meldung nur bei mir? Wenn ja ist es nicht so schlimm, wenn es dafür an der Hochschule funktioniert. 

Bei create -s kommt immer "can´t find directory" line 157
und bei delete kommt gar keine Meldung es passiert nur nichts.

Wenn das nur an meinem System liegt ist es nicht so schlimm.

**Comment by KasikciMu** [comment]
Bei mir funktioniert alles fehlerfrei!
Nur bei Create ist das einzige Problem, dass wenn ich Create -c aufrufe es ein Archiv erstellt aber anstatt das es so ist:

C:\Users\Kasikci\Desktop\Perl Programme\Archiv\C_Users_Kasikci_Desktop_Perl_Programme_Test_2015_01_12_00_50_52\{Die zu archivierenden Daten}

ist es so:
C:\Users\Kasikci\Desktop\Perl Programme\Archiv\C_Users_Kasikci_Desktop_Perl_Programme_Test_2015_01_12_00_50_52\C_Users_Kasikci_Desktop_Perl_Programme_Test\{Die zu archivierenden Daten}

@Ramunno könntest du das bitte fixen!
Ansonsten läuft bei meinem PC alles einwandfrei!

**Comment by VPatrick** [comment]
Fehler tritt bei mir und auf dem Referenz-PC nicht mehr auf!
