### ISSUE TITLE
Can't locate loadable object for module Win32::Shortcut

### ISSUE THREAD

**Issue by VPatrick** [VPatrick/PerlArchiver#29]
@KasikciMu , @mia8287 , @Ramunno 

Hi ich teste grad am Referenz-PC aber es kommt folgende Fehlermeldung:

Can't locate loadable object for module Win32::Shortcut in @INC (@INC contains: dirname(dirname abs_path $0) . "/PerlArchiver/source" /Users/pvogt/Dropbox/TH Nürnberg/5. Semester/SysProgPerl/PerlArchiver/PerlArchiver/source /Library/Perl/5.18/darwin-thread-multi-2level /Library/Perl/5.18 /Network/Library/Perl/5.18/darwin-thread-multi-2level /Network/Library/Perl/5.18 /Library/Perl/Updates/5.18.2 /System/Library/Perl/5.18/darwin-thread-multi-2level /System/Library/Perl/5.18 /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level /System/Library/Perl/Extras/5.18) at del.pm line 8.

Folgende Seite erklärt den Fehler etwas besser: http://www.perlmonks.org/?node_id=807603

**Comment by VPatrick** [comment]
Hab mal die Delete-Klasse im Invoker auskommentiert und dann funktionierts!

**Comment by mia8287** [comment]
Hast du mal versucht den Pfad direkt anzugeben statt dirname(dirname abs_path $0) . "/PerlArchiver/source" ?

**Comment by mia8287** [comment]
bzw den Win32 Ordner von mir weggelassen?

**Comment by Ramunno** [comment]
Warum habt ihr den Win32 Ordner erstellt? Bei mir geht es ohne!

**Comment by mia8287** [comment]
Ich hab ihn nur mal zur Vorsorge rein, da ich nicht weiß ob es an der Hochschule mit cygwin perl 5.14 geht.

**Comment by Ramunno** [comment]
Aso, aber nicht das die anderen Fälle dann nicht mehr funktionieren.

**Comment by VPatrick** [comment]
Mit Cygwin Perl 5.14 ging das Delete nicht.
Das hat dann die Fehlermeldung beim Kompilieren verursacht und die anderen Fälle haben dann nicht mehr funktioniert!

**Comment by mia8287** [comment]
In der Fehlermeldung steht was von perl 5.16 war das ein anderer PC?
In create werden auch win32 shortcuts verwendet, geht das ohne Probleme?
Ich werde es mir nach meiner Prüfung mal ansehen, was ich da noch machen kann. Das Modul wurde ja schließlich vom Hein vorgeschlagen.
