### ISSUE TITLE
Dokumentation

### ISSUE THREAD

**Issue by VPatrick** [VPatrick/PerlArchiver#3]
Architekturentwurf im Wiki dokumentieren und mit Diagrammen beschreiben.

**Comment by VPatrick** [comment]
##### Invoker:
* verbosity : Verbosity (Klassenvariable --> Verbosity-Objekt)
* setVerboseLevel(level : int)
* create (arguments : array)
* slim (arguments : array)
* restore (arguments : array)
* del (arguments : array)
* list (arguments : array)
* help()

##### Verbosity:
* level : int (Klassenvariable)
* setVerboseLevel(level : int)
* verbose(message : string, [state : string])
* colourise(state : string)

##### List:
* list(directory : string)
* traverse(dir : string, margin : int)

Die Klasse List ist noch nicht ganz fertig. Da können sich also noch Methoden bzw. Variablen ändern.

Zur Verwendung von Verbosity: Erstellt euch einfach im Konstruktor eurer Klasse ein Verbosity-Objekt (siehe Invoker) und ruft die Methode verbose(...) auf. Der Methode könnt ihr eure Nachricht und einen von drei Status übergeben ("OK", "WARNING", "ERROR"). Wenn die Konsole Farben unterstützt werden dann farbige Texte [OK] (grün), [WARNING] (gelb), [ERROR] (rot) ausgegeben.

**Comment by KasikciMu** [comment]
Also bei mir hat sich folgendes verändert:

gelöscht wurde:
* _Verbose
* addVerbose()
* Verbose()

hinzugekommen sind:
* Klassenvariable verbosity : Verbosity-Objekt
* setVerboseLevel(level : int)

**Comment by mia8287** [comment]
Delete

Klassenvariablen:
deleteFile : string
mainArchivpath : string
archivFullName : string
archivName : string
verbosity 

Methoden:
-new(inDeleteFile : string)
-init(self : hash)
-findPreDir(self : hash)
-findLinksPreDir(self : hash, preDir : string)
-checkLink(self : hash, allLnkFiles : array)
-changeLnks(self : hash, newLnk : string, newDat : string, foundDir : array)
-newLink(self : hash, newDat : string, newLinks : hash)
-del(self : hash)

**Comment by KasikciMu** [comment]
globale Attribute:
* FinalTime: datetime
Attribute
* source: String
* sourcename:String
* destination: String
* usertime: datetime
* partial: String
* rel_path: {0,1}
* verbosity: Verbostiy-Objekt

Methode:
* new()
* addSource(Source:String)
* addDestination(Destination:String)
* addSourceName(Sourcename:String)
* addUserTime(Usertime:datetime)
* addPartial(Partial:String)
* setVerboseLevel(level:int)
* restore_r()
* restore_rp()
* Find_source_rp(Directory: String, partial:String)
* RestoreDirectory(SourceArchiv:String)
* DestinationArchiv(Destination:String, SourceName:String)
* RestoreSubDirectory(Source:string, Destination:String)
* RestoreFile(Source:string, Destination:string)
* DirectoryUp(tmp:string)
* DESTROY()

Meine Klasse greift auf die Verbosity-Klasse zu 
und die Utilis-Klasse.Verwendete Funktionen aus Utilis:
* findLastValidArchive(source:String,timestamp:datetime))

**Comment by KasikciMu** [comment]
Die Methode DirectoryUp kannst rauslöschen

**Comment by Ramunno** [comment]
@KasikciMu 
Sind deine Attribute alle private?
Sind deine Methoden alle public?
Ist es richtig das keiner deiner Methoden einen Rückgabewert hat?
Bei verbosity erzeugst du ein neues Objekt, oder?

**Comment by Ramunno** [comment]
@KasikciMu 
usertime: datetime? datetime = String oder?
rel_path: {0,1}?  {0,1} =  Boolean oder String?

**Comment by Ramunno** [comment]
FinalTime: datetime Attribute? datetime = String oder?

**Comment by KasikciMu** [comment]
bei allen datetime -> string
rel_path auch string

ALLE Attribute sind private

public Methoden:
* new()
* ALLE add...() methoden

Der Rest sind alles private

Methoden mit Rückgabewert:
* Find_source_rp() -> string
* DestinationArchiv() -> string

**Comment by Ramunno** [comment]
Laut Quellcode ist keine deiner Methode private.
private Methoden werden in Variablen gespeichert.
z.B. so 
my $createDir = sub{....}

**Comment by Ramunno** [comment]
our $FinalTime; ist auch nicht private

**Comment by KasikciMu** [comment]
Dann wäre ja jede Subroutine public
Mach dann einfach alles public ist mir sowas von egal solange irgendwas drinnen steht
Bei Perl gibts doch sowas wie "private" und "public" nicht deshalb find ich es sinnlos das überhaupt anzugeben

**Comment by Ramunno** [comment]
Doch in Perl gibt es public und private.
Jede Methode ist zunächst public, wenn du die Methode in einer Variablen speicherst die mit my deklariert ist, dann wird sie private.
Du kannst dann nur noch in deiner Klasse auf die Methode zugreifen.
Macht schon ein großen Unterschied. So könnte jeder Benutzer dein Klasse Methoden ausführen, die er nicht Ausführen darf!

**Comment by KasikciMu** [comment]
Dann wären wohl alle meine Methoden public

**Comment by Ramunno** [comment]
Ja, und das sollte eigentlich nicht sein!

**Comment by KasikciMu** [comment]
Ich will hier etz nichts mehr groß ändern die anderen Methoden schaden ja keinem

**Comment by KasikciMu** [comment]
@Ramunno 
Sonst noch irgendwas weil ich bin den restlichen Abend nicht mehr erreichbar

**Comment by KasikciMu** [comment]
Ansonsten hätte ich gesagt ich bereite meine Präsentation morgen vor und stell sie auf Github

**Comment by Ramunno** [comment]
@VPatrick 
In <b>list</b>
Hast du +list(directory : string) geändert? Laut Code sieht die Methode so aus: +list(archive:String, timestamp:String)

**Comment by VPatrick** [comment]
@Ramunno  So siehts aus: +list(archive:String, timestamp:String)
List hat jetzt auch einen Destruktor

**Comment by Ramunno** [comment]
Klassendiagramm ist jetzt auf dem neusten Stand und Hochgeladen unter Diagramme.
Bitte mal anschauen ob alles passt!
Danke!

**Comment by VPatrick** [comment]
In der Klasse Utils hat sich folgendes Verändert: Referenz auf das Message-Objekt (Assoziation, oder so)

**Comment by VPatrick** [comment]
Ich hab mal mit der Dokumentation angefangen. Könnt ihr mir eure Teile der Dokumentation schicken, dann kann ich das alles in einem Dokument zusammenfassen. Den bisherigen Stand der Doku findet ihr als PDF hier: https://github.com/VPatrick/PerlArchiver/tree/master/Dokumente

Zu den Platzhaltern **[Beschreibung ...]** brauch ich dann noch von euch die Beschreibung der Methoden, Diagramme plus Beschreibung etc. Was euch halt einfällt und notiert werden muss.

**Comment by VPatrick** [comment]
Folgende Änderungen hat's gegeben:

Utils:
* - message : Message (Klassenvariable)
* + getPathFromHash(hash : string, path : string) : string
* + getAbsPath(path : string) : string

Invoker:
* - utils : Utils (Klassenvariable)
* + printHashTable(arguments : array)

**Comment by KasikciMu** [comment]
Folgendes hat sich in meiner Klasse geändert:
globales Attribut:
* +Flag:boolean

Methorden:
* -DirectoryUp
* +FindArchive()
* +getLinkPath(linkName : String, linkPath : String)

**Comment by Ramunno** [comment]
Da ich sonst keine weiteren Änderungen bekommen habe. Erstelle ich das endgültig Klassendiagramm und lade es hoch.

**Comment by Ramunno** [comment]
Klassendiagramm aktualisiert und Übersicht erstellt (ohne Methoden)

**Comment by Ramunno** [comment]
Die Klassendiagramme in der Doku müssen angepasst werden.

**Comment by Ramunno** [comment]
@VPatrick Kannst du nicht die Doku im original hochladen, dann können Fehler die einem auffallen, direkt verbessert werden.

**Comment by VPatrick** [comment]
Könnt ich schon aber Pages kann die Michaela nicht und der Muhammed hat vermutlich nicht die aktuelle Version. Außerdem kommt GitHub anscheinend nicht so gut mit solchen Formaten zurecht. Wenn ich eure Teile eingebaut hab, dann schick ich euch die Doku im Original (.pages/.docx) per Mail. Dann könnt ihr noch Fehler verbessern etc und bis dahin könnt ihr doch einfach hier ein paar Kommentare schreiben (Fehler auf Seite 9; fehlerhafter Satz => verbesserter Satz)

**Comment by VPatrick** [comment]
Ich lad immer zeitnah die aktuelle Version hoch

**Comment by VPatrick** [comment]
@Ramunno Kannst du das Klassendiagramm für die Übersicht mehr in die Länge ziehen. Ich kann das leider nicht vergrößern weils so breit ist aber so kann man nahezu nichts erkennen. Einfach die Klassen ein wenig umsortieren, das es höher und schmäler wird.

**Comment by Ramunno** [comment]
@VPatrick Ich hab die Übersicht leider nicht mehr gespeichert. Habe nur noch die detaillierte Ansicht

**Comment by VPatrick** [comment]
Hm... Kannst du die nochmal machen oder sollen wir's so lassen?

**Comment by Ramunno** [comment]
Könnte schon, aber das ewig gedauert. Und eigentlich hab ich da keine Lust drauf. Ich muss ja noch die Doku schreiben.

**Comment by VPatrick** [comment]
Musst du wissen. Der wird uns wegen dem Klassendiagramm bestimmt kei schlechtere Note geben.

**Comment by Ramunno** [comment]
Kann es sein das GitHub noch nicht eincheckte Sachen löscht. Bei mir ist mein Doku komplett weg!

**Comment by VPatrick** [comment]
Also GitHub löscht nix von allein. Was sein kann, ist das deine Dateien bei einem Merge gelöscht wurden.

**Comment by Ramunno** [comment]
Vielleicht hat ja einer ein Verzeichnis umbenannt, oder verschoben! Ich habe auf jeden Fall nichts gemacht und die Datei ist weg!

**Comment by VPatrick** [comment]
Da kann ich dir leider nicht weiterhelfen. Wie hieß die Datei und in welchem Verzeichnis hätte die sein sollen? Meine Empfehlung ist ja, nur PDFs auf GitHub zu laden und Word oder Pages-Dateien auf dem lokalen System zu belassen.

**Comment by Ramunno** [comment]
Ja die Datei war ja nur lokal, aber halt im Verzeichnis vom git

**Comment by Ramunno** [comment]
@all Mal ne Frage macht ihr zu jeder Methode ein Aktivitätsdiagramm?

**Comment by VPatrick** [comment]
Nein

**Comment by KasikciMu** [comment]
Nein

**Comment by Ramunno** [comment]
Oh ich schon :-)
@VPatrick Kannst du das Klassendiagramm nicht im Querformat machen, so das es eine ganze Seite ausfüllt, sonst erkennt man echt nicht. Umsortieren geht nicht wirklich, sind zuviel Verbindungen!

**Comment by Ramunno** [comment]
@VPatrick Nicht sichtbare Hassdatei auf Seite 4 oben ausbessern. Ist sichtbar!

**Comment by Ramunno** [comment]
Soll ich dann eigentlich mein Doku als PDF oder Pages Datei hochladen?

**Comment by VPatrick** [comment]
@Ramunno Du erstellst 22 Aktivitätsdiagramme? Die Dokumentation soll fei nur 18 - 20 Seiten lang werden. Schick mir die Pages-Datei bitte per Email. Wenn du willst kannst du auch ein PDF ins Repository laden aber die Email möchte ich trotzdem.

**Comment by VPatrick** [comment]
@all Hab das mit der "nicht sichtbaren Hashdatei" korrigiert.

**Comment by KasikciMu** [comment]
@VPatrick 
Wer dokumentiert die Utils Klasse ^^ :)

**Comment by VPatrick** [comment]
@KasikciMu 
Wieso soll die Stils-Klasse dokumentiert werden? Ist doch nur ne Hilfsklasse und ist kommentiert aber wir könnens gern so machen.

**Comment by KasikciMu** [comment]
@VPatrick 
Wäre dann ein ganz kurzer Abschnitt.
Wenigstens wir haben es bisschen erklärt.

**Comment by Ramunno** [comment]
Naja das Create ist ein bisschen aufwendiger und wenn ich das alles in Prosa erkläre, dann steigt kein Mensch durch! Außerdem soll er sich nicht so anstellen sind ja alles nur Bilder ;-).
@VPatrick  Du solltest die Diagramm nicht als png einfügen, die sind viel zu unscharf! Öffne einfach das PDF in Vorschau und markiere den Abschnitt den du haben willst, und dann mach Copy & Paste.
Dadurch wird es als Vektorgrafik eingefügt. Das kann man dann auch schön zoomen!

**Comment by Ramunno** [comment]
Ich habe dir die Doku geschickt. Hab dir aus Versehen zuerst die falsche Datei geschickt!

**Comment by VPatrick** [comment]
@Ramunno Wir sollten auf 18 - 20 Seiten kommen. Im Moment haben wir ohne Deckblatt, Inhaltsverzeichnis und Anhang ca. 8 Seiten. Du musst deine Doku etwas kürzer fassen. Ich kann so nicht alles übernehmen sonst wird das Dokument zu lang. Die anderen müssen ihre Klassen ja auch noch beschreiben. Das Profiling sollte auch erwähnt werden.

@Ramunno Werd das mit den Vektorgrafiken berücksichtigen. Wusste ich bis dato gar nicht :)

@KasikciMu Ich glaube nicht, dass wir Utils mit aufnehmen können. Wir kommen wahrscheinlich überhaupt nicht mit den 20 Seiten hin. Es wird viel zu viel werden. Wenn am Schluss no irgendwo Platz ist, dann kann ich als Lückenfüller vielleicht ein paar Sätze dazu schreiben.

Wir müssen mit der Seitenzahl aufpassen!

**Comment by VPatrick** [comment]
@Ramunno  Er hat in der Aufgabenstellung klar geschrieben, dass detaillierte Diagramme in den Anhang sollen.

**Comment by KasikciMu** [comment]
@VPatrick 
Ich weiß nicht auf wie viele Seiten @Ramunno gekommen ist aber bei Restore komme ich auf höchsten 2 Seiten XD

**Comment by Ramunno** [comment]
Da steht aber auch das der Programmfluss Dokumentiert werden soll.
" Beschreiben Sie die Verwendung (User Guide) sowie das Design der Software (data structures, modules, packages, subroutines, <b>program flow</b>, etc.). Hinweis: Programm- fluss kann übersichtlich mit UML Aktivitäts-Diagrammen dargestellt werden."
Die anderen Diagramm die du meinst wären Datenstrukturen, detaillierte UML-Diagramme, etc.
Ich wüsste nicht was ich da kürzen soll. Da steht ja eh nur das nötigste.
Kurze Erklärung was Create macht.
Die Sicht des Entwickler-Anwender.
Die Sicht des Weiterentwicklers.
So wie er es das letzte mal gesagt hat!

**Comment by VPatrick** [comment]
@Ramunno Aber du erkennst doch das Problem, dass wir wenn ich deine 10 Seiten so einfüge schon bei 18 Seiten sind und die anderen ihre Teile auch noch beschreiben müssen.
Du kannst dich ja mal beim Hein schlau machen, ob die Seitenzahl nur das Mindestmaß ist, also ob wir auch mehr als 20 Seiten schreiben dürfen. Wenn dem so ist, dann hab ich kein Problem damit aber anderenfalls muss dein Part kürzer werden!

**Comment by KasikciMu** [comment]
@Ramunno HAHAHA Hast du Schriftgröße 30 genommen XD

**Comment by Ramunno** [comment]
@VPatrick Warum fragst du Ihn nicht? Ich habe irgendwie nicht so einen guten Draht zu Ihm! Kannst du mir erzählen was ich an der Doku kürzen soll.
Ich beschreibe nur die Methoden, in einem Satz, dann noch Parameter und Rückgabewerte.
Dann wie man die Use-Case verwendet.
Und was Create überhaupt macht.
Ich sehe da kein Kürzungspotenzial.
Hatte er nicht mal gemeint das es keine Fixe Seitenzahl ist?
Du kannst ja die Diagramm vielleicht ein bisschen verkleinern oder anders anordnen.
Außerdem sind es nur 9 Seiten!

**Comment by Ramunno** [comment]
Ich hab die Doku von Create auf git hochgeladen.
https://github.com/VPatrick/PerlArchiver/blob/master/Dokumente/Dokumentation%20Create.pdf

**Comment by VPatrick** [comment]
Hab dem Hein grad ne Mail geschrieben ob wir auch mehr als 20 Seiten schreiben dürfen.
 ----------------------------------------
Sehr geehrter Herr Hein,

ich hätte eine Frage bezüglich der Seitenanzahl der Projektdokumentation von unserem Archivierungsprojekt in Systemprogrammierung mit Perl.
In Ihrer Aufgabenstellung ist die angegebene Seitenzahl 18 - 20 Seiten.
Ist dies das Mindestmaß oder dürfen wir auch mehr schreiben?
Im Moment kommen wir, wie aussieht, wohl auf knapp 30 Seiten (mit Diagrammen und der Beschreibung aus Sicht eines normalen Anwenders, eines Administrator und eines Entwicklers).

Mit freundlichen Grüßen,
Patrick Vogt

**Comment by KasikciMu** [comment]
@VPatrick 
Welche E-Mail Adresse :D

**Comment by Ramunno** [comment]
Alles klar dann bin ich mal gespannt!

**Comment by KasikciMu** [comment]
@VPatrick @Ramunno @mia8287 
Welche Schriftart verwenden wir oder machst es @VPatrick ?

**Comment by VPatrick** [comment]
Ich kümmere mich um Schriftart, Größe, Zeilenabstand, Einzüge, ...

**Comment by Ramunno** [comment]
@VPatrick Lade mal die Pages-Datei hoch. Die Dokumentation hat einige Fehler innen. Ich bessere es mit Änderungsverfolgung aus. Die Abstände sind viel zu groß und muss das Profiliga 4 Seiten haben?

**Comment by Ramunno** [comment]
Außerdem haben wir noch 6 Seiten frei!

**Comment by VPatrick** [comment]
Habs hochgeladen. Machs gleich ohne Änderungsverfolgung, dann muss ich das nicht mehr nachtragen.
Wenn du noch Material zum Füllen für die 6 Seiten hast, dann kannst es gleich rein machen und lass das Profiling doch 4 Seiten haben.

**Comment by Ramunno** [comment]
Hab das Design mal angepasst, haben jetzt 11,5 Seiten ohne Anhang, Deckblatt und Inhaltsverzeichnis.
Wollte nochmal wegen sonstige Fehler durchschauen, aber erst morgen oder so!

**Comment by mia8287** [comment]
Könnte jemand die aktuelle Doku von heute Mittag in pdf hochladen?

**Comment by Ramunno** [comment]
Ich hab das aktuelle hochgeladen.
https://github.com/VPatrick/PerlArchiver/blob/master/Dokumente/DOKUMENTATION.pdf

**Comment by mia8287** [comment]
@Ramunno 
Habe meine Doku hochgeladen. Sind 3 Seiten inkl. Diagramm.

**Comment by mia8287** [comment]
Auf Seite 2 sollte noch die Beschreibung geändert werden, damit man weiß dass der Pfad mit angegeben werden muss

> perl my_perl_archive.pl [-v] -d [Zu löschendes Objekt mit Pfadangabe]

**Comment by Ramunno** [comment]
Soll ich vielleicht die Übersicht des Klassendiagramms in den Anhang machen oder entfernen? Reicht ja eigentlich das Detaillierte, oder?

**Comment by Ramunno** [comment]
Dokumentation ist fertig.
Ich habe es hier angelegt: https://github.com/VPatrick/PerlArchiver/blob/master/ABGABE/Documentation/Dokumentation%20Projektarbeit%20Archivierung.pdf
Schaut mal an ob es so passt.

**Comment by KasikciMu** [comment]
Bericht wurde abgegeben :D

**Comment by Ramunno** [comment]
Sehr gut!
@VPatrick Hast du die Doku und den Code schon geschickt?

**Comment by Ramunno** [comment]
Muss unter CaseStudies nicht noch die Ergebnisse vom Profiling?

**Comment by VPatrick** [comment]
@Ramunno Ergebnisse vom Profiling sind mit eingefügt und die Mail ist soeben (15:05 Uhr) an den Hein raus!
