### ISSUE TITLE
Underscore im Verzeichnisname

### ISSUE THREAD

**Issue by VPatrick** [VPatrick/PerlArchiver#30]
mögliche Lösung:
* Hashen
* Rainbowtable

**Comment by Ramunno** [comment]
Verzeichnisse sind schon als Hash umgesetzt. Bitte testen!

**Comment by KasikciMu** [comment]
Folgendes Problem bei mir mit den Hashes
Solange ich einen Hash nicht "enthashen" kann brauch ich das Quellverzeichnis.
Bei Restore wird es eben nicht mit angegeben, weil man wiederherstellen kann wohin man will.

**Comment by VPatrick** [comment]
@Ramunno 
Wenn du Verzeichnisse mit Hashes erstellst, dann schreib bitte die Hashes in ne Datei (Rainbow-Table).
Form sollte irgendwie so sein:
habe837625$5837:PFAD

Das Trennzeichen sollte ein Zeichen sein, dass nicht im Hash und auch nicht im Pfad vorkommt. Hab den Doppelpunkt jetzt diesbezüglich nicht geprüft.

**Comment by Ramunno** [comment]
Was wollt ihr genau haben?
Hash_date:Verzeichnis
oder
Verzeichnis:Hash_date

Der : ist weder unter Unix noch unter Windows erlaubt. Allerdings wird hier ein Pfad gespeichert, d.h. der Pfad beginnt ja mit C: oder D:.
Wie wäre es wenn wir es so abspeichern?
Hash_date:<Verzeichnis>

**Comment by KasikciMu** [comment]
Ich bin da leidenschaftslos ich brauch einfach nur den Archivnamen damit ich weiß welches Archiv ich wiederherstellen soll

**Comment by mia8287** [comment]
Für mich wäre es wichtig, dass das Archiv immer mit yyyy_mm_dd_hh_ii_ss endet, damit ich die richtigen Ordner in der richtigen Reihenfolge einlese und dass Archive mit dem gleichen Quellordner den gleichen Namen haben. 
Denkt ihr es ist ok, wenn das Archiv dann den Hash im Namen hat? Wäre ja auch nicht nutzerfreundlich, wenn man ein bestimmtes Archiv sucht und dann erst in einer Datei nachsehen muss welcher Hash es ist.

**Comment by KasikciMu** [comment]
Wir können es auch so gestalten, dass zum Beispiel der Anweder einfach nur den switch angibt und dann das Programm die einzelnen Parameter abfrägt.
z.b. bei Restore:
* Geben Sie das Quellverzeichniss an: C:\Users\Hein\Archiv (oder relativer Pfad)
* Danach liest das Programm die Datei aus und gibt die vorhandenen Archive aus sodass der Anweder aus den genannten Archiven wählen kann.
* Geben Sie das Zielverzeichniss an: C\Users\Hein\Data (oder relativer Pfad)
* Geben Sie die Zeit an ... usw

Meinungen?

**Comment by VPatrick** [comment]
Ich wäre für Hash_date:Pfad, dann kann man beim ersten Doppelpunkt splitten und hat beide teile.

Die Sache mit der Benutzerführung was wann eingegeben werden soll find ich zum jetzigen Zeitpunkt zu aufwendig. Das würde ja mir im Invoker zufallen aber ich hab die Zeit nicht mehr wirklich dafür.
Muss noch für sieben Klausuren lernen und für zwei Projektarbeiten die Doku schreiben. Schaff da das andere einfach nicht.

LG Patrick

**Comment by mia8287** [comment]
Das mit den splitten nach dem : ist nicht möglich, da das Zeichen im Namen garnicht erlaubt ist.
Wie wäre es mit Hash_Quellordner_Zeit (also s3jb3jfb3_Dokumente_2015_01_15_11_12_34), man sieht so, um welches Archiv es sich handeln könnte und es wäre einmalig.

**Comment by mia8287** [comment]
und für den genauen Pfad kann man dan in einer Textdatei nachsehen.

**Comment by Ramunno** [comment]
Die Idee vom Muhammed finde ich ganz gut mit dem schrittweise angeben. Denn eigentlich ist es ja nicht die Aufgabe der einzelnen Klassen das eingegeben zu interpretieren, sondern die des Invokers.
Der Invoker ist dafür verantwortlich die Aufgaben richtig zu verteilen. Er ist ja sozusagen der Controller.

@VPatrick Klausuren schreiben wir alle, ich schreibe z.B. morgen auch 2

@mia8287 Das mit dem Quellordner nach dem Hash finde ich keine gute Idee. Dadurch haben wir keinen weiteren Informationsgewinn. Ich könnte ja in verschieden Ordnern das Verzeichnis Dokumente haben.

Ich würde vorschlagen das wir es mit der Datei machen, in die Datei wird der Hash:Quellverzeichnis geschrieben. Jedes Duellverzeichnis bekommt einen Eintrag.
Der Invoker müsste nur das Quellverzeichnis hashen und nachschauen ob dieses in der Datei vorhanden ist.
Bei Restore könnte einfach das zu Wiederherstellende Verzeichnis angegeben werden, dass wird dann gehasht und nachgeschaut ob es einen Eintrag dafür gibt. Wenn ja kann der Invoker den Hash_date an Restore übergeben.

**Comment by Ramunno** [comment]
Außerdem sollten wir uns spätestens am Montag nochmal treffen und alles in der TH testen. Bis dahin muss alles laufen!
Ich werde Änderungen erst am Wochenende einbringen können, muss noch lernen!
Wenn ihr wünsch habt, dann bitte bis spätestens Freitag mitteilen.

**Comment by Ramunno** [comment]
Der : soll nur zum splitten in der Textdatei sein.
Der Ordner besteht nur aus Hash und Datum also so d22cd2cc059d_2015_01_13_21_27_37
Übrigens der Hash ist ein MD5 und Hexadezimal

**Comment by VPatrick** [comment]
Also ich würde dann die Quellverzeichnisse (lt. Eingabe) hashen, in der Tabelle nachsehen und euch dann den entsprechenden Pfad übergeben?

Die "Benutzerführung" kann ich leider aus zeitgründen nicht mehr umsetzen. Wenn ihr noch mehr Zeit habt als ich, dann dürft ihr das gerne im Invoker implementieren.

**Comment by VPatrick** [comment]
@Ramunno 
Wo kann ich die Datei mit den Hash-Pfad-Zuordnungen finden?

**Comment by Ramunno** [comment]
Ich habe die Erstellung der Hash Zuordnung fertig.
Die Datei wir im Archivverzeichnis erstellt. z.B. C:\Users\Home\Desktop\source\TestArchiv
Testet mal bitte ob es richtig funktioniert!
War sonst noch etwas bei Create zu ändern?

**Comment by Ramunno** [comment]
Erledigt
