### ISSUE TITLE
Profiling: Ausgangssituation genau angeben

### ISSUE THREAD

**Issue by VPatrick** [VPatrick/PerlArchiver#33]
* Mittlere Dateigröße
* Anzahl Dateien/Verzeichnisse
* Fallstudie KEIN statistisch, etc

**Comment by Ramunno** [comment]
Kannst das endgültige Profiling für Create machen.

**Comment by VPatrick** [comment]
Für List kannst auch ein endgültiges Profiling machen.

**Comment by VPatrick** [comment]
Wenn du Lust hast kannst du auch ein Profiling für den Switch -m (Mapping) machen. Der ist da um die Abbildungstabelle auszugeben. Da werden wir aber wahrscheinlich keine interessanten Ergebnisse zu Gesicht bekommen.

**Comment by KasikciMu** [comment]
@Ramunno 
Eine Frage zu Create_s:
Bei dem Profiling erstelle ich immer Test Programme womit ich jede Klasse einzeln testen kann, also nicht über my_perl_archive.pl. Da ist mir aufgefallen als ich Create_s testen wollte habe ich ganz normal den Pfad zu den Archiven angegeben: "C:\Users\Hein\Archiv"
und den Namen des zu verschlankenden Archivs: "Test"
Leider hat er nichts gemacht. Nachdem ich für den Archivnamen den Hash angegeben hatte hat es funktioniert. Ich wollte nachfragen ob sich das so gehört oder ob ich irgendwas verpasst habe.

**Comment by VPatrick** [comment]
@KasikciMu Warum erstellst du extra Test-Programme? Mach doch einfach mit my_perl_archive.pl und dem passenden Switch oder hat des Nachteile?

**Comment by VPatrick** [comment]
@KasikciMu Wir haben die Funktion -s auf die Angabe eines Archivs, also Hash mit Timestamp, geändert. Ich extrahier aus dem Archiv-Verzeichnis den Archivnamen raus.

**Comment by KasikciMu** [comment]
@VPatrick 
Ich will die reinen Ergebnisse von den Klassen haben.
Es wird sowieso schon vom Profiling etwas verfälscht, deshalb mach ich das so.

**Comment by VPatrick** [comment]
Aso, ok.
