### ISSUE TITLE
Verwendung von absoluten UND relativen Pfaden

### ISSUE THREAD

**Issue by VPatrick** [VPatrick/PerlArchiver#34]

**Comment by KasikciMu** [comment]
Weiß irgendwer wie man des mit einer Zeile macht ich hab nur die rel2abs()- Methode gefunden und des einzige was die macht ist dem relativen Pfad ein "C:\" vorne anzuhängen ^^

**Comment by VPatrick** [comment]
Das kann ich dir leider nicht sagen, aber ich wechsle mit chdir in ein neues Verzeichnis und gib mir dann mit Cwd::getcwd() das aktuelle Arbeitsverzeichnis als absoluten Pfad aus. Die Eingaben können aber relative oder absolute Pfade sein.

**Comment by VPatrick** [comment]
@Ramunno 
Was erwartet dein Create, absolute oder relative Pfade? Muss den Invoker dementsprechend anpassen.

**Comment by Ramunno** [comment]
Create erwartet absolute Pfade. Löst der Invoker dann die relativen Pfade auf?

**Comment by Ramunno** [comment]
Create müsste jetzt auch mit relativen Pfaden funktionieren

**Comment by Ramunno** [comment]
Bist du dir sicher das getAbsPath richtig funktioniert?
Ich hab das bei mir so umgesetzt:
use Cwd 'abs_path';
my $absolutePath = abs_path($source);

**Comment by VPatrick** [comment]
Es funktioniert zumindest unter Mac. Windows kann ich erst am Montag in der TH testen.
