### ISSUE TITLE
Verbose-Ausgabe bei Delete detaillierter

### ISSUE THREAD

**Issue by VPatrick** [VPatrick/PerlArchiver#35]

**Comment by mia8287** [comment]
@VPatrick 
Wird ERROR und WARNING auch angezeigt, wenn Verbose nicht gesetzt ist?

**Comment by mia8287** [comment]
@VPatrick Hat sich erledigt

**Comment by VPatrick** [comment]
Wenn du ERROR oder WARNING ausgeben willst, dann kannst du die Klasse `Message` benutzen. Die stellt drei Methoden `error(message)`, `warning(message)` und `ok(message)` bereit.

**Comment by VPatrick** [comment]
@mia8287 
Warum verwendest du in folgender Zeile:
`print "\[ERROR\]\tNo such file or directory:\n\t$self->{deleteFile}!";`
Nicht die error()-Methode aus der Klasse Message, die dir das ERROR schreibt und es, wenn unterstützt auch rot einfärbt?

**Comment by mia8287** [comment]
Die Ausgabe werde ich morgen noch überarbeiten, es war mir erstmal wichtig, dass es geht. Die Farben sieht man doch unter Windows eh nicht oder?

**Comment by VPatrick** [comment]
Unter Windows sieht man's nicht, das stimmt aber auf allen *nix-Systemen wird's dann farbig.
