### ISSUE TITLE
Hilfe

### ISSUE THREAD

**Issue by Ramunno** [VPatrick/PerlArchiver#37]
Die Hilfe sollte die benötigten Parameter der einzelnen Funktionen enthalten.
z.B. create -c : Benötigt Quellverzeichnis und Zielverzeichnis
       Beispiel: create -c [Quellverzeichnis] [Zielverziechnis]
Ansonsten kann keiner was damit anfangen, nicht mal ich mit den anderer Funktionen wie delete, Restore.

**Comment by VPatrick** [comment]
@Ramunno , @KasikciMu , @mia8287 
Könnt ihr mir bitte die Parameter eurer Methoden beschreiben. Z. B.: -c [Quellverzeichnis] [Zielverzeichnis]
