### ISSUE TITLE
utils.pm getAbsPath

### ISSUE THREAD

**Issue by mi-ela** [VPatrick/PerlArchiver#38]
Die Sub müsste bei mir so aussehen sonst funktioniert delete nicht mehr:

sub getAbsPath {
    my ($self, $path) = @_;
    return Cwd::abs_path($path);
};

Es darf kein chdir gemacht werden, da ich kein Verzeichnis löschen kann in dem ich dann arbeite. Wenn eine Datei gelöscht werden soll funktioniert chdir auch nicht.

**Comment by Ramunno** [comment]
Das ist genau das Problem das ich in Issue #34 angesprochen habe

**Comment by VPatrick** [comment]
Erledigt
